"""Hugging Face Hub compatibility checker, PR generator, and badge markdown builder."""

from typing import Dict, Optional
from adapterbridge.core.inspector import AdapterInspector
from adapterbridge.models.report import ValidationReport


def generate_hf_badge_markdown(target_engine: str = "vllm", is_compatible: bool = True) -> str:
    """Generate AdapterBridge Certified badge markdown for Hugging Face model cards."""
    status_text = f"{target_engine.upper()}%20Compatible" if is_compatible else f"{target_engine.upper()}%20Incompatible"
    color = "brightgreen" if is_compatible else "red"
    badge_url = f"https://img.shields.io/badge/AdapterBridge-{status_text}-{color}.svg"
    repo_url = "https://github.com/adapterbridge/adapterbridge"

    return f"[![AdapterBridge Certified]({badge_url})]({repo_url})"


def generate_hf_pr_description(report: ValidationReport) -> str:
    """Generate Pull Request description for Hugging Face model repository fixes."""
    badge = generate_hf_badge_markdown(target_engine=report.target_engine, is_compatible=True)
    lines = [
        "## 🛠️ Automated AdapterBridge Compatibility Fix",
        "",
        f"{badge}",
        "",
        f"Hey! We noticed this PEFT LoRA adapter lacked base model metadata required for direct **{report.target_engine.upper()}** serving.",
        "",
        "### Applied Remediation Operations:",
        "- Synthesized missing `config.json` base model metadata.",
        "- Injected architecture-appropriate Jinja2 `chat_template` in `tokenizer_config.json`.",
        "- Normalized tensor key prefixes (`base_model.model.model.` -> `model.`).",
        "",
        "This pull request makes the checkpoint ready for zero-friction serving on vLLM and SGLang runtimes.",
        "",
        "*Generated by [@AdapterBridge-Bot](https://github.com/adapterbridge/adapterbridge)*",
    ]
    return "\n".join(lines)
